---
- hosts: all
  vars:
    - reinstall_homebrew: 'False'
  roles:
    - default-packages
    - aws
    - oh-my-zsh
    - docker
    - mac-osx-dock

#    - name: Start services at login
#      file: src=/usr/local/opt/{{ item }}/homebrew.mxcl.{{ item }}.plist path=~/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist state=link force=yes
#      with_items: 
#       - neo4j