---
# This role configures aws credentials file
  - stat: path={{ aws_user_folder }}
    register: aws_user_folder_exists

  - name: Create .aws folder if it doesn't exist
    file: state=directory path={{ aws_user_folder }} group=staff
    when: aws_user_folder_exists.stat.exists == False

  - name: Create AWS Credentials file
    template: src=templates/aws_credentials.j2 dest={{ aws_credentials_location }} group=staff mode=0644
    when: aws_user_folder_exists.stat.exists == False