---

- name: Install virtualbox for docker
  homebrew_cask: name={{ item }} state=present
  with_items:
    - virtualbox

- name: remove old docker
  homebrew: name={{ item }} state=absent
  with_items:
    - docker
    - boot2docker

- name: Install docker toolbox for docker on MacOSX
  homebrew_cask: name={{ item }} state=present
  with_items:
    - docker-toolbox